# Generated by Django 5.1 on 2024-09-03 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0004_user_watchlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="listings",
            field=models.ManyToManyField(
                related_name="listing_category", to="auctions.listing"
            ),
        ),
    ]
