# Generated by Django 5.1 on 2024-09-03 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0005_category_listings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="listings",
            field=models.ManyToManyField(
                blank=True, related_name="listing_category", to="auctions.listing"
            ),
        ),
    ]
